name: 'deployment'
on:
  push:
    branches:
     - development
jobs:
  test:
    runs-on: ['macos-latest']
    steps:
      - name: Get the code.
        uses: actions/checkout@v5
      - name: Install node.
        uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: Install the dependencies.
        run: npm install
      - name: Run Tests.
        run: npm test
      - name: Finish Test job.
        run: echo "Completed the Test job successfully."
  build:
    runs-on: ['macos-latest']
    steps:
      - name: Get the code
        uses: actions/checkout@v5
      - name: Install node.
        uses: actions/setup-node@v4
        with:
            node-version: 23
      - name: Install the dependencies.
        run: npm install
      - name: Build the code. 
        run: npm run build
      - name: Generate unique build ID for each build.
        id: generate_build_id
        run: |
          BUILD_ID="${{github.sha}}-${{github.run_number}}"
          echo "BUILD_ID=$BUILD_ID" >> GITHUB_OUTPUT
      - name: Publish the JS filename
        run: find build/static/js -type f -name "*.js" -print0 | xargs -0 echo "build_job_output=$(cat)" >> "$GITHUB_OUTPUT"
      - name: Upload artifacts for the build job of the application.
        uses: actions/upload-artifact@v4
        with: 
          name: portfolio-application-build
          path: ./build
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
      - name: Verify the uploaded files.
        run: ls
      - name: Finish Build job.
        run: echo "Completed the Build job successfully."
  deploy:
    needs: [build, test]
    runs-on: ['macos-latest']
    permissions: 
      pages: write
      id-token: write
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Get the code.
        uses: actions/checkout@v5
      - name: Install node.
        uses: actions/setup-node@v4
        with: 
          node-version: 23
      - name: Install the dependencies.
        run: npm install
      - name: Download the build job artifacts to use in deployment job.
        uses: actions/download-artifact@v4
        with:
          name: portfolio-application-build
          path: ./build
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hiddeb-files: false
      - name: Verify the downloaded artifacts.
        run: ls
      - name: Deploy the application to github pages.
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          artifact_name: portfolio-application-build
      - name: Finish Deploy job.
        run: |
           echo "Completed the Deploy job successfully."
           echo "Live URL: ${{ steps.deployment.outputs.hosting-website }}"


